---
title: "BST260 Final Project RMarkdown"
author: "Yanran, Yunan"
date: "2020/12/3"
output: html_document
---

### Customer Revenue Data Exploration

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(ggplot2)
library(zoo)
library(h2o)
library(caret)
library(lme4)
library(ggalluvial)
library(xgboost)
library(jsonlite)
library(knitr)
library(Rmisc)
library(scales)
library(countrycode)
library(highcharter)
library(glmnet)
library(keras)
library(forecast)
library(magrittr)
```

### Load data
```{r, message=FALSE}
# Read the Customer Revenue data for further 

# for further reference:
# training data: train
# testing data: test
# submission data: subm

train <- read_csv("train.csv")
test <- read_csv("test.csv")
submission <- read_csv("sample_submission.csv")
```

### Reshaping Data

```{r}
set.seed(0)
head(test)
unique(train$socialEngagementType)
```

### Reshaping Data

```{r}
# printing out the first five rows of te and tr for further exploration
head(train,5)
head(test,5)

```


As we can see from above, device, geoNetwork, trafficSource, totals are all in JSON format, hence the next step we need to is to deal with the JSON data.

```{r message=FALSE, warning=FALSE, results='hide'}

# here since I am referring back to the link:
# https://www.kaggle.com/mrlong/r-flatten-json-columns-to-make-single-data-frame
# https://www.kaggle.com/kailex/r-eda-for-gstore-glm-keras-xgb
# in terms of transfroming the netted json file into single data frame
# as we can see from the above dataframe, for the json data, it is delimited by ,

train_device <- paste("[", paste(train$device, collapse = ","), "]") %>% fromJSON(flatten = T)
train_geoNetwork <- paste("[", paste(train$geoNetwork, collapse = ","), "]") %>% fromJSON(flatten = T)
train_totals <- paste("[", paste(train$totals, collapse = ","), "]") %>% fromJSON(flatten = T)
train_trafficSource <- paste("[", paste(train$trafficSource, collapse = ","), "]") %>% fromJSON(flatten = T)

test_device <- paste("[", paste(test$device, collapse = ","), "]") %>% fromJSON(flatten = T)
test_geoNetwork <- paste("[", paste(test$geoNetwork, collapse = ","), "]") %>% fromJSON(flatten = T)
test_totals <- paste("[", paste(test$totals, collapse = ","), "]") %>% fromJSON(flatten = T)
test_trafficSource <- paste("[", paste(test$trafficSource, collapse = ","), "]") %>% fromJSON(flatten = T)
```

```{r message=FALSE, warning=FALSE, results='hide'}
# sanity check upon the dealing with the json file
head(train_device, 5)
head(test_device, 5)
```